### ISSUE TITLE
Please update docker-registry-rpm to 2.6.2

### ISSUE THREAD

**Issue by patsevanton** [abn/docker-registry-rpm#1]
Hello!
Please update docker-registry-rpm to 2.6.2
Thank you

**Comment by patsevanton** [comment]
https://github.com/abn/docker-registry-rpm/pull/2

**Comment by abn** [comment]
Merged. See comments on #2.

**Comment by abn** [comment]
@patsevanton also note that fedora now includes the `docker-distribution` package in its official repository.

See: https://src.fedoraproject.org/rpms/docker-distribution

**Comment by patsevanton** [comment]
OMG
and i build docker-distribution for EL7
https://copr-be.cloud.fedoraproject.org/results/antonpatsev/docker-distribution/epel-7-x86_64/00704465-docker-distribution/

**Comment by abn** [comment]
:+1:
